version: '3'

services:

  #React Nextjs Node Service

  node:

    image: webskittersdocker/node12:latest

    container_name: basic_setup-node12

    restart: unless-stopped

    working_dir: /home/wtsadmin/myapp

    environment:

      - NODE_ENV=production

    
    volumes:

      - ./:/home/wtsadmin/myapp

    ports:

      - "1111:1111"
    command: >
      sh -c "npm install &&
             npm start"


#Docker Networks
#Docker Networks

networks:
  default:
    external:
      name: webskitters
